language: scala
scala:
  - 2.11.11
  - 2.12.4
os: osx
osx_image: xcode9.3
jdk:
  - oraclejdk8
env:
  - SBT_OPTS="-Xmx3G -XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled -Xss2M"
before_install:
  - brew update && brew bundle
script:
  - sbt clean coverage test coverageReport coverageAggregate
after_success:
  - bash <(curl -s https://codecov.io/bash)