version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: openjdk:8
#    environment:
#      - SBT_VERSION: 0.13.16
    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - run:
          name: Get sbt binary
          command: |
                    apt update && apt install -y curl
                    curl -L -o sbt-0.13.16.deb https://dl.bintray.com/sbt/debian/sbt-0.13.16.deb
                    dpkg -i sbt-0.13.16.deb
                    rm sbt-0.13.16.deb
                    apt-get update
                    apt-get install -y sbt python-pip git
                    pip install awscli
                    apt-get clean && apt-get autoclean
      - checkout
      - run:
          name: Compile samplescala dist package
          command: cat /dev/null | sbt clean coverage test coverageReport coverageAggregate