version: 2
jobs:
  build:
    working_directory: ~/repo
    machine: true
    environment:
      - SBT_VERSION: 0.13.16
      - JVM_OPTS: -Xms4G -Xmx4G -Xss6M -XX:MaxMetaspaceSize=1G -XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled
      - SBT_OPTS: -Xmx4G -XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled -Xss2M

    steps:
      - run:
          name: Get sbt binary
          command: |
                    apt update && apt install -y curl
                    curl -L -o sbt-$SBT_VERSION.deb https://dl.bintray.com/sbt/debian/sbt-$SBT_VERSION.deb
                    sudo dpkg -i sbt-$SBT_VERSION.deb
                    rm sbt-$SBT_VERSION.deb
                    sudo apt-get update
                    sudo apt-get install -y sbt python-pip git
                    sudo pip install awscli
                    sudo apt-get clean && apt-get autoclean
      - checkout
      - run:
          name: Running tests and generate coverage report
          command: cat /dev/null | sbt clean coverage test coverageReport coverageAggregate
      - run:
          name: Publish coverage report
          command: bash <(curl -s https://codecov.io/bash)